export const IPC = {
  getVault: 'vault:get',
  saveDetail: 'vault:save-detail',
  removeDetail: 'vault:remove-detail',
  updateProfile: 'vault:update-profile',
  updatePreferences: 'vault:update-preferences',
  addDocuments: 'vault:add-documents',
  saveDocument: 'vault:save-document',
  removeDocument: 'vault:remove-document',
  openDocument: 'vault:open-document',
  saveDocumentAs: 'vault:save-document-as',
  startDocumentDrag: 'vault:start-document-drag',
  getDocumentPreview: 'vault:get-document-preview',
  pickDocuments: 'vault:pick-documents',
  exportArchive: 'vault:export-archive',
  importArchive: 'vault:import-archive',
  copyText: 'vault:copy-text',
  showWidget: 'window:show-widget',
  hideWidget: 'window:hide-widget',
  showMain: 'window:show-main',
  navigate: 'window:navigate',
  changed: 'vault:changed',
  quickAdd: 'vault:quick-add'
} as const
